### ISSUE TITLE
Retries sometimes fails w/o logging

### ISSUE THREAD

**Issue by zieren** [zieren/eltern-emailer#39]
ISTM the program can crash in the retry (outer) loop. There is no log info, possibly because it's not flushed.

**Comment by zieren** [comment]
```
2023-03-20T19:38:54.745Z error: Error in main loop:
Error: Navigation failed because browser has disconnected!
    at d:\tmp\eltern-emailer\node_modules\puppeteer\lib\cjs\puppeteer\common\LifecycleWatcher.js:51:147
    at d:\tmp\eltern-emailer\node_modules\puppeteer\lib\cjs\vendor\mitt\src\index.js:51:62
    at Array.map (<anonymous>)
    at Object.emit (d:\tmp\eltern-emailer\node_modules\puppeteer\lib\cjs\vendor\mitt\src\index.js:51:43)
    at CDPSession.emit (d:\tmp\eltern-emailer\node_modules\puppeteer\lib\cjs\puppeteer\common\EventEmitter.js:72:22)
    at CDPSession._onClosed (d:\tmp\eltern-emailer\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:271:14)
    at Connection._onClose (d:\tmp\eltern-emailer\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:144:21)
    at WebSocket.<anonymous> (d:\tmp\eltern-emailer\node_modules\puppeteer\lib\cjs\puppeteer\node\NodeWebSocketTransport.js:17:30)
    at WebSocket.onClose (d:\tmp\eltern-emailer\node_modules\ws\lib\event-target.js:210:18)
    at WebSocket.emit (node:events:520:28)
2023-03-20T19:38:54.806Z debug: Logged out of IMAP server
2023-03-20T19:38:54.807Z debug: Closed IMAP connection
2023-03-20T19:38:54.807Z debug: Last failure was 5944.419 seconds ago
2023-03-20T19:38:54.807Z info: Waiting 15 seconds before retry
2023-03-21T07:58:48.958Z debug: Waiting completed
2023-03-21T07:58:49.354Z info: Eltern-Emailer 0.4.0 (c) 2022-2023 Jörg Zieren, GNU GPL v3. See https://zieren.de/software/eltern-emailer for component license info
2023-03-21T07:58:49.597Z error: IMAP: {"err":{"errno":-3008,"code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"outlook.office365.com"},"cid":"1245f7tyd9j0q0p28d36"}
2023-03-21T07:58:49.876Z info: Awakening main loop
2023-03-21T07:58:50.053Z error: IMAP server not found
2023-03-21T07:58:50.206Z info: Exiting with code 4
```
