### ISSUE TITLE
Error in readNoticeBoard: Found 4 subjects, but 6 contents

### ISSUE THREAD

**Issue by matgoebl** [zieren/eltern-emailer#77]
readNoticeBoard fails, because attachments are counted as content items.
```
error: Error in processElternPortal:                                                                                                                                   
Error: Found 4 subjects, but 6 contents                                                                                                                                                    
    at readNoticeBoard (/home/pptruser/elternportal.js:512:11)                                                                                                                             
    at async processElternPortal (/home/pptruser/elternportal.js:948:3)                                                                                                                    
    at async tryProcess (/home/pptruser/main.js:329:5)                                                                                                                                     
    at async main (/home/pptruser/main.js:425:11)                                                                                                                                          
    at async /home/pptruser/main.js:486:22
```

Changing the selector from `~` to `+` works:
![2024-11-16-091537_903x414_scrot](https://github.com/user-attachments/assets/437e8e13-b781-4d53-b377-a5eb76430e50)

**Comment by matgoebl** [comment]
My current working solution is https://github.com/zieren/eltern-emailer/commit/8749ed73d13d67fdd49a528404743dd143ffd241

**Comment by matgoebl** [comment]
Oh - bad!
This produces duplicates :-(
Some id tracking issue, I guess.

**Comment by matgoebl** [comment]
tried a fix in https://github.com/zieren/eltern-emailer/commit/8749ed73d13d67fdd49a528404743dd143ffd241 + https://github.com/matgoebl/eltern-emailer/commit/a3fb7a44e10d7421e2cc205093bc8a73094c54c3

**Comment by zieren** [comment]
@matgoebl Can you give this a try? It works for me and the example you emailed me.

**Comment by matgoebl** [comment]
Hello @zieren , your mentioned fix bbc8859 works.
I double checked: if its in, the application can read the noticeboard. When I revert the commit, it fails as expected with
```
2025-03-21 21:24:06 error: Error in processElternPortal:
Error: Found 3 subjects, but 4 contents
    at readNoticeBoard (/home/pptruser/elternportal.js:512:11)
    at async processElternPortal (/home/pptruser/elternportal.js:948:3)
    at async tryProcess (/home/pptruser/main.js:329:5)
    at async main (/home/pptruser/main.js:425:11)
    at async /home/pptruser/main.js:486:22
```
